### ISSUE TITLE
vim-plug supports any git url

### ISSUE THREAD

**Issue by dchinmay2** [ksyasuda/lsp_lines.nvim#1]
https://github.com/junegunn/vim-plug#example

> `Plug 'https://github.com/junegunn/vim-github-dashboard.git'`

**Comment by ksyasuda** [comment]
Yeah you're right.  Thanks for pointing this out.  I don't know why I had assumed that it couldn't, but I'm in the process of converting my config to lua, so I've moved over to packer anyway.  I think for now I'll leave the repo up for comparability and to help give this project whatever visibility I can
